"""empty message

Revision ID: 047f86b2dfca
Revises: f73d2aeef721
Create Date: 2017-11-30 16:44:04.313654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '047f86b2dfca'
down_revision = 'f73d2aeef721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_pic', sa.String(length=255), nullable=True))
    op.add_column('tags', sa.Column('tag_pic', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('head_pic', sa.String(length=255), nullable=True))
    op.drop_column('users', 'status')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=300), nullable=True))
    op.add_column('users', sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('users', 'head_pic')
    op.drop_column('tags', 'tag_pic')
    op.drop_column('posts', 'post_pic')
    # ### end Alembic commands ###
