"""empty message

Revision ID: eeec45dc5702
Revises: 047f86b2dfca
Create Date: 2017-11-30 18:14:46.055887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeec45dc5702'
down_revision = '047f86b2dfca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwd', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passwd')
    # ### end Alembic commands ###
