"""empty message

Revision ID: f3aaac16f553
Revises: 86798246a173
Create Date: 2017-11-20 14:51:10.072567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3aaac16f553'
down_revision = '86798246a173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('pid', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'pid')
    # ### end Alembic commands ###
