"""empty message

Revision ID: f73d2aeef721
Revises: f3aaac16f553
Create Date: 2017-11-20 15:29:55.839668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73d2aeef721'
down_revision = 'f3aaac16f553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'code')
    # ### end Alembic commands ###
